package com.ee.lab.tuning.control;

import com.ee.lab.tuning.entity.PoolStatistics;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import com.zaxxer.hikari.HikariPoolMXBean;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;

public class DataSourceManager {

    private static final Logger LOGGER = Logger.getLogger(DataSourceManager.class.getName());

    private final HikariDataSource dataSource;
    private final String profileName;

    public DataSourceManager(String profileName, int maxPoolSize, int minIdle, long connectionTimeoutMs) {
        this.profileName = profileName;
        HikariConfig config = new HikariConfig();
        config.setPoolName("HikariPool-" + profileName);
        config.setJdbcUrl("jdbc:h2:mem:" + profileName.toLowerCase() + ";DB_CLOSE_DELAY=-1");
        config.setUsername("sa");
        config.setPassword("");
        config.setMaximumPoolSize(maxPoolSize);
        config.setMinimumIdle(minIdle);
        config.setConnectionTimeout(connectionTimeoutMs);
        config.setIdleTimeout(30000);
        config.setMaxLifetime(60000);

        this.dataSource = new HikariDataSource(config);
        initSchema();
        LOGGER.info(String.format("Initialized HikariCP datasource [%s]: maxPoolSize=%d, minIdle=%d, timeout=%dms",
                profileName, maxPoolSize, minIdle, connectionTimeoutMs));
    }

    private void initSchema() {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS audit_events (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "cluster_node VARCHAR(64) NOT NULL, " +
                    "status_code INT NOT NULL, " +
                    "recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
            
            // Seed initial 50 records
            try (PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO audit_events (cluster_node, status_code) VALUES (?, ?)")) {
                for (int i = 1; i <= 50; i++) {
                    ps.setString(1, "node-eu-west-" + (i % 5));
                    ps.setInt(2, 200);
                    ps.addBatch();
                }
                ps.executeBatch();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database schema", e);
        }
    }

    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }

    public PoolStatistics getPoolStatistics() {
        HikariPoolMXBean poolMx = dataSource.getHikariPoolMXBean();
        if (poolMx != null) {
            return new PoolStatistics(
                    profileName,
                    poolMx.getTotalConnections(),
                    poolMx.getActiveConnections(),
                    poolMx.getIdleConnections(),
                    poolMx.getThreadsAwaitingConnection(),
                    dataSource.getMaximumPoolSize(),
                    dataSource.getMinimumIdle()
            );
        }
        return new PoolStatistics(profileName, 0, 0, 0, 0, dataSource.getMaximumPoolSize(), dataSource.getMinimumIdle());
    }

    public int executeQuery(long simulatedDbLatencyMs) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE status_code = ?")) {
            ps.setInt(1, 200);
            if (simulatedDbLatencyMs > 0) {
                try {
                    Thread.sleep(simulatedDbLatencyMs);
                } catch (InterruptedException ignored) {
                    Thread.currentThread().interrupt();
                }
            }
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        }
        return 0;
    }

    public void close() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
            LOGGER.info("Closed datasource [" + profileName + "]");
        }
    }
}
